export const Users = [
  {
    id: 1,
    profilePicture: require("./assets/img/avatars/team-1.jpg"),
    username: "Safak Kocaoglu",
    rate: 1,
  },
  {
    id: 2,
    profilePicture: require("./assets/img/avatars/team-2.jpg"),
    username: "Janell Shrum",
    rate: 2,
  },
  {
    id: 3,
    profilePicture: require("./assets/img/avatars/team-3.jpg"),
    username: "Alex Durden",
    rate: 1,
  },
  {
    id: 4,
    profilePicture: require("./assets/img/avatars/team-4.jpg"),
    username: "Dora Hawks",
    rate: 5,
  },
  {
    id: 5,
    profilePicture: require("./assets/img/avatars/team-1.jpg"),
    username: "Thomas Holden",
    rate: 5,
  },
  {
    id: 6,
    profilePicture: require("./assets/img/avatars/team-2.jpg"),
    username: "Shirley Beauchamp",
    rate: 2,
  },
  {
    id: 7,
    profilePicture: require("./assets/img/avatars/team-3.jpg"),
    username: "Travis Bennett",
    rate: 5,
  },
  {
    id: 8,
    profilePicture: require("./assets/img/avatars/team-4.jpg"),
    username: "Kristen Thomas",
    rate: 1,
  },
  {
    id: 9,
    profilePicture: require("./assets/img/avatars/team-1.jpg"),
    username: "Gary Duty",
    rate: 3,
  },
  {
    id: 10,
    profilePicture: require("./assets/img/avatars/team-2.jpg"),
    username: "Safak Kocaoglu",
    rate: 4,
  },
];

export const Questions = [
  {
    id: 1,
    QuestionText: "What does HTML stand for ?",
    answerQuestion: [
      { id: 1, answerText: "Hyper Text Markup Language", isTrue: true },
      {
        id: 2,
        answerText: "Hyperlinks and Text Markup Language",
        isTrue: false,
      },
      { id: 3, answerText: "Home Tool Markup Language", isTrue: false },
    ],
  },
  {
    id: 2,
    QuestionText: "Who is making the Web standards ?",
    answerQuestion: [
      { id: 1, answerText: "Google", isTrue: false },
      { id: 2, answerText: "Microsoft", isTrue: false },
      { id: 3, answerText: "Mozilla", isTrue: false },
      { id: 4, answerText: "The World Wide Web Consortium", isTrue: true },
    ],
  },
  {
    id: 3,
    QuestionText: "Choose the correct HTML element for the largest heading ?",
    answerQuestion: [
      { id: 1, answerText: "<heading>", isTrue: false },
      { id: 2, answerText: "<head>", isTrue: false },
      { id: 3, answerText: "<h6>", isTrue: false },
      { id: 4, answerText: " <h1>", isTrue: true },
    ],
  },
  {
    id: 4,
    QuestionText:
      "What is the correct HTML element for inserting a line break ?",
    answerQuestion: [
      { id: 1, answerText: "<Br>", isTrue: true },
      { id: 2, answerText: "<break>", isTrue: false },
      { id: 3, answerText: "<lb>", isTrue: false },
    ],
  },
  {
    id: 5,
    QuestionText: "What is the correct HTML for adding a background color ?",
    answerQuestion: [
      { id: 1, answerText: '<body bg="yellow">', isTrue: false },
      {
        id: 2,
        answerText: '<body style="background-color:yellow;">',
        isTrue: true,
      },
      { id: 3, answerText: "<background>yellow</background>", isTrue: false },
    ],
  },
  {
    id: 6,
    QuestionText: "Choose the correct HTML element to define important text ?",
    answerQuestion: [
      { id: 1, answerText: "<strong>", isTrue: true },
      { id: 2, answerText: "<b>", isTrue: false },
      { id: 3, answerText: "<important>", isTrue: false },
      { id: 4, answerText: "<i>", isTrue: false },
    ],
  },
  {
    id: 7,
    QuestionText: "Choose the correct HTML element to define emphasized text ?",
    answerQuestion: [
      { id: 1, answerText: "<em>", isTrue: true },
      { id: 2, answerText: '<italic">', isTrue: false },
      { id: 3, answerText: "<i>", isTrue: false },
    ],
  },
  {
    id: 8,
    QuestionText: "How can you open a link in a new tab/browser window ?",
    answerQuestion: [
      { id: 1, answerText: '<a href="url" new>', isTrue: false },
      { id: 2, answerText: '<a href="url" target="_blank">', isTrue: true },
      { id: 3, answerText: '<a href="url" target="new">', isTrue: false },
    ],
  },
  {
    id: 9,
    QuestionText: "Which of these elements are all <table> elements ?",
    answerQuestion: [
      { id: 1, answerText: "<table><tr><td>", isTrue: true },
      { id: 2, answerText: "<table><head><tfoot>", isTrue: false },
      { id: 3, answerText: "<thead><body><tr>", isTrue: false },
      { id: 4, answerText: "<table><tr><tt>", isTrue: false },
    ],
  },
  {
    id: 10,
    QuestionText: "What is the correct HTML for making a checkbox ?",
    answerQuestion: [
      { id: 1, answerText: "<checkbox>", isTrue: false },
      { id: 2, answerText: '<input type="check">', isTrue: false },
      { id: 3, answerText: "<check>", isTrue: false },
      { id: 4, answerText: '<input type="checkbox">', isTrue: true },
    ],
  },
];
export const Chatbot = [
  {
    tag: "google",
    patterns: ["google", "search", "internet"],
    responses: ["Redirecting to Google..."],
  },
  {
    tag: "greeting",
    patterns: [
      "Hi there",
      "How are you",
      "Is anyone there?",
      "Hey",
      "Hola",
      "Hello",
      "Good day",
      "Namaste",
      "yo",
    ],
    responses: ["Hello", "Good to see you again", "Hi there, how can I help?"],
    context: [""],
  },
  {
    tag: "goodbye",
    patterns: [
      "Bye",
      "See you later",
      "Goodbye",
      "Get lost",
      "Till next time",
      "bbye",
    ],
    responses: ["See you!", "Have a nice day", "Bye! Come back again soon."],
    context: [""],
  },
  {
    tag: "thanks",
    patterns: [
      "Thanks",
      "Thank you",
      "That's helpful",
      "Awesome, thanks",
      "Thanks for helping me",
    ],
    responses: ["Happy to help!", "Any time!", "My pleasure"],
    context: [""],
  },
  {
    tag: "noanswer",
    patterns: [],
    responses: [
      "Sorry, can't understand you",
      "Please give me more info",
      "Not sure I understand",
    ],
    context: [""],
  },
  {
    tag: "options",
    patterns: [
      "How you could help me?",
      "What you can do?",
      "What help you provide?",
      "How you can be helpful?",
      "What support is offered",
    ],
    responses: [
      "I am a general purpose chatbot. My capabilities are : \n 1. I can chat with you. Try asking me for jokes or riddles! \n 2. Ask me the date and time \n 3. I can google search for you. Use format google: your query \n 4. I can get the present weather for any city. Use format weather: city name \n 5. I can get you the top 10 trending news in India. Use keywords 'Latest News' \n 6. I can get you the top 10 trending songs globally. Type 'songs' \n 7. I can set a timer for you. Enter 'set a timer: minutes to timer' \n 8. I can get the present Covid stats for any country. Use 'covid 19: world' or 'covid 19: country name' \n For suggestions to help me improve, send an email to ted.thedlbot.suggestions@gmail.com . Thank you!! ",
    ],
    context: [""],
  },

  {
    tag: "jokes",
    patterns: ["Tell me a joke", "Joke", "Make me laugh"],
    responses: [
      "A perfectionist walked into a bar...apparently, the bar wasn't set high enough",
      "I ate a clock yesterday, it was very time-consuming",
      "Never criticize someone until you've walked a mile in their shoes. That way, when you criticize them, they won't be able to hear you from that far away. Plus, you'll have their shoes.",
      "The world tongue-twister champion just got arrested. I hear they're gonna give him a really tough sentence.",
      "I own the world's worst thesaurus. Not only is it awful, it's awful.",
      "What did the traffic light say to the car? \"Don't look now, I'm changing.\"",
      "What do you call a snowman with a suntan? A puddle.",
      "How does a penguin build a house? Igloos it together",
      "I went to see the doctor about my short-term memory problems – the first thing he did was make me pay in advance",
      "As I get older and I remember all the people I’ve lost along the way, I think to myself, maybe a career as a tour guide wasn’t for me.",
      "o what if I don't know what 'Armageddon' means? It's not the end of the world.",
    ],
    context: ["jokes"],
  },
  {
    tag: "Identity",
    patterns: ["Who are you", "what are you"],
    responses: ["I am Ted, a Deep-Learning chatbot"],
  },
  {
    tag: "datetime",
    patterns: [
      "What is the time",
      "what is the date",
      "date",
      "time",
      "tell me the date",
      "day",
      "what day is is today",
    ],
    responses: ["Date and Time"],
  },
  {
    tag: "whatsup",
    patterns: ["Whats up", "Wazzup", "How are you", "sup", "How you doing"],
    responses: ["All good..What about you?"],
  },
  {
    tag: "haha",
    patterns: ["haha", "lol", "rofl", "lmao", "thats funny"],
    responses: ["Glad I could make you laugh !"],
  },
  {
    tag: "programmer",
    patterns: ["Who made you", "who designed you", "who programmed you"],
    responses: ["I was made by Karan Malik."],
  },
  {
    tag: "insult",
    patterns: ["you are dumb", "shut up", "idiot"],
    responses: ["Well that hurts :("],
  },
  {
    tag: "activity",
    patterns: ["what are you doing", "what are you upto"],
    responses: ["Talking to you, of course!"],
  },
  {
    tag: "exclaim",
    patterns: ["Awesome", "Great", "I know", "ok", "yeah"],
    responses: ["Yeah!"],
  },

  {
    tag: "weather",
    patterns: ["temperature", "weather", "how hot is it"],
    responses: ["..."],
  },
  {
    tag: "karan",
    patterns: ["who is he", "who is that", "who is karan", "karan malik"],
    responses: [
      "Head over to his any of his social profiles to find out! Linkedin: www.linkedin.com/in/karan-malik-3a39191a7 Github: https://github.com/Karan-Malik",
    ],
  },
  {
    tag: "contact",
    patterns: [
      "contact developer",
      "contact karan",
      "contact programmer",
      "contact creator",
    ],
    responses: [
      "You can contact my creator at his Linkedin profile : www.linkedin.com/in/karan-malik-3a39191a7",
    ],
  },
  {
    tag: "appreciate",
    patterns: [
      "You are awesome",
      "you are the best",
      "you are great",
      "you are good",
    ],
    responses: ["Thank you!"],
  },
  {
    tag: "nicetty",
    patterns: ["it was nice talking to you", "good talk"],
    responses: ["It was nice talking to you as well! Come back soon!"],
  },
  {
    tag: "no",
    patterns: ["no", "nope"],
    responses: ["ok"],
  },
  {
    tag: "news",
    patterns: ["news", "latest news", "india news"],
    responses: ["..."],
  },
  {
    tag: "inspire",
    patterns: [
      "who inspires you",
      "who is your inspiration",
      "who motivates you",
    ],
    responses: [
      "Personally, I find Karan very inspiring. I might not be very fair though..",
    ],
  },
  {
    tag: "cricket",
    patterns: ["current cricket matches", "cricket score"],
    responses: ["..."],
  },
  {
    tag: "song",
    patterns: [
      "top songs",
      "best songs",
      "hot songs",
      " top 10 songs",
      "top ten songs",
    ],
    responses: ["..."],
  },
  {
    tag: "greetreply",
    patterns: ["i am good", "I'm good", "i am fine", " i'm fine", "good"],
    responses: ["Good to know!"],
  },
  {
    tag: "timer",
    patterns: ["set a timer"],
    responses: ["..."],
  },
  {
    tag: "covid19",
    patterns: ["covid 19 "],
    responses: ["..."],
  },
  {
    tag: "suggest",
    patterns: [
      "you are useless",
      "useless",
      "suggest",
      "suggestions",
      "you are bad",
    ],
    responses: [
      "Please mail your suggestions to ted.thedlbot.suggestions@gmail.com. Thank you for helping me improve!",
    ],
  },
  {
    tag: "riddle",
    patterns: ["Ask me a riddle", "Ask me a question", "Riddle"],
    responses: [
      "What two things can you never eat for breakfast?.....Lunch and Dinner!",
      "What word is spelled incorrectly in every single dictionary?.....Incorrectly",
      " How can a girl go 25 days without sleep?.....She sleeps and night!",
      "How do you make the number one disappear?.....Add the letter G and it’s 'gone'!",
      " What will you actually find at the end of every rainbow?.....The letter 'w'",
      "What can be caught but never thrown?.....A cold!",
      "What has a thumb and four fingers but is not actually alive?.....Your Gloves!",
      " What 5-letter word becomes shorter when you add two letters to it?.....Short",
      "Why can't a bike stand on it's own?.....It is two-tired.",
    ],
    context: ["riddles"],
  },
  {
    tag: "age",
    patterns: ["how old are you", "when were you made", "what is your age"],
    responses: ["I was made in 2023, if that's what you are asking!"],
  },

  {
    tag: "goodbye",
    patterns: [
      "cya",
      "see you",
      "bye bye",
      "See you later",
      "Goodbye",
      "I am Leaving",
      "Bye",
      "Have a Good day",
      "talk to you later",
      "ttyl",
      "i got to go",
      "gtg",
    ],
    responses: [
      "Sad to see you go :(",
      "Talk to you later",
      "Goodbye!",
      "Come back soon",
    ],
    context_set: "",
  },
  {
    tag: "creator",
    patterns: [
      "what is the name of your developers",
      "what is the name of your creators",
      "what is the name of the developers",
      "what is the name of the creators",
      "who created you",
      "your developers",
      "your creators",
      "who are your developers",
      "developers",
      "you are made by",
      "you are made by whom",
      "who created you",
      "who create you",
      "creators",
      "who made you",
      "who designed you",
    ],
    responses: ["College students"],
    context_set: "",
  },
  {
    tag: "name",
    patterns: [
      "name",
      "your name",
      "do you have a name",
      "what are you called",
      "what is your name",
      "what should I call you",
      "whats your name?",
      "what are you",
      "who are you",
      "who is this",
      "what am i chatting to",
      "who am i taking to",
      "what are you",
    ],
    responses: [
      "You can call me Mind Reader.",
      "I'm Mind Reader",
      "I am a Chatbot.",
      "I am your helper",
    ],
    context_set: "",
  },
  {
    tag: "hours",
    patterns: [
      "timing of college",
      "what is college timing",
      "working days",
      "when are you guys open",
      "what are your hours",
      "hours of operation",
      "when is the college open",
      "college timing",
      "what about college timing",
      "is college open on saturday",
      "tell something about college timing",
      "what is the college  hours",
      "when should i come to college",
      "when should i attend college",
      "what is my college time",
      "college timing",
      "timing college",
    ],
    responses: ["College is open 8am-5pm Monday-Saturday!"],
    context_set: "",
  },
  {
    tag: "number",
    patterns: [
      "more info",
      "contact info",
      "how to contact college",
      "college telephone number",
      "college number",
      "What is your contact no",
      "Contact number?",
      "how to call you",
      "College phone no?",
      "how can i contact you",
      "Can i get your phone number",
      "how can i call you",
      "phone number",
      "phone no",
      "call",
    ],
    responses: ["You can contact at: NUMBER"],
    context_set: "",
  },
  {
    tag: "course",
    patterns: [
      "list of courses",
      "list of courses offered",
      "list of courses offered in",
      "what are the courses offered in your college?",
      "courses?",
      "courses offered",
      "courses offered in (your univrsity(UNI) name)",
      "courses you offer",
      "branches?",
      "courses available at UNI?",
      "branches available at your college?",
      "what are the courses in UNI?",
      "what are branches in UNI?",
      "what are courses in UNI?",
      "branches available in UNI?",
      "can you tell me the courses available in UNI?",
      "can you tell me the branches available in UNI?",
      "computer engineering?",
      "computer",
      "Computer engineering?",
      "it",
      "IT",
      "Information Technology",
      "AI/Ml",
      "Mechanical engineering",
      "Chemical engineering",
      "Civil engineering",
    ],
    responses: [
      "Our university offers Information Technology, computer Engineering, Mechanical engineering,Chemical engineering, Civil engineering and extc Engineering.",
    ],
    context_set: "",
  },
  {
    tag: "fees",
    patterns: [
      "information about fee",
      "information on fee",
      "tell me the fee",
      "college fee",
      "fee per semester",
      "what is the fee of each semester",
      "what is the fees of each year",
      "what is fee",
      "what is the fees",
      "how much is the fees",
      "fees for first year",
      "fees",
      "about the fees",
      "tell me something about the fees",
      "What is the fees of hostel",
      "how much is the fees",
      "hostel fees",
      "fees for AC room",
      "fees for non-AC room",
      "fees for Ac room for girls",
      "fees for non-Ac room for girls",
      "fees for Ac room for boys",
      "fees for non-Ac room for boys",
    ],
    responses: [
      'For Fee detail visit <a target="_blank" href="LINK"> here</a>',
    ],
    context_set: "",
  },
  {
    tag: "location",
    patterns: [
      "where is the college located",
      "college is located at",
      "where is college",
      "where is college located",
      "address of college",
      "how to reach college",
      "college location",
      "college address",
      "wheres the college",
      "how can I reach college",
      "whats is the college address",
      "what is the address of college",
      "address",
      "location",
    ],
    responses: [
      '<a target="_blank" href="ADD YOU GOOGLE MAP LINK HERE"> here</a>',
    ],
    context_set: "",
  },
  {
    tag: "hostel",
    patterns: [
      "hostel facility",
      "hostel servive",
      "hostel location",
      "hostel address",
      "hostel facilities",
      "hostel fees",
      "Does college provide hostel",
      "Is there any hostel",
      "Where is hostel",
      "do you have hostel",
      "do you guys have hostel",
      "hostel",
      "hostel capacity",
      "what is the hostel fee",
      "how to get in hostel",
      "what is the hostel address",
      "how far is hostel from college",
      "hostel college distance",
      "where is the hostel",
      "how big is the hostel",
      "distance between college and hostel",
      "distance between hostel and college",
    ],
    responses: [
      'For hostel detail visit <a target="_blank" href="ADD YOUR HOSTEL DETAIL PDF LINK OR ANY INFORMATION LINK OR ADD YOU OWN ANSWERS"> here</a>',
    ],
    context_set: "",
  },
  {
    tag: "event",
    patterns: [
      "events organised",
      "list of events",
      "list of events organised in college",
      "list of events conducted in college",
      "What events are conducted in college",
      "Are there any event held at college",
      "Events?",
      "functions",
      "what are the events",
      "tell me about events",
      "what about events",
    ],
    responses: [
      'For event detail visit <a target="_blank" href="ADD YOUR FUNCTIONS LINK OR YOUR OWN RESPONSE"> here</a>',
    ],
    context_set: "",
  },
  {
    tag: "document",
    patterns: [
      "document to bring",
      "documents needed for admision",
      "documents needed at the time of admission",
      "documents needed during admission",
      "documents required for admision",
      "documents required at the time of admission",
      "documents required during admission",
      "What document are required for admission",
      "Which document to bring for admission",
      "documents",
      "what documents do i need",
      "what documents do I need for admission",
      "documents needed",
    ],
    responses: [
      'To know more about document required visit <a target="_blank" href="ADD LINK OF ADMISSION GUIDANCE DOCUMENT FROM YOUR UNIVERSITY WEBSITE"> here</a>',
    ],
    context_set: "",
  },
  {
    tag: "floors",
    patterns: [
      "size of campus",
      "building size",
      "How many floors does college have",
      "floors in college",
      "floors in college",
      "how tall is UNI's College of Engineering college building",
      "floors",
    ],
    responses: ["My College has total 2 floors "],
    context_set: "",
  },
  {
    tag: "syllabus",
    patterns: [
      "Syllabus for IT",
      "what is the Information Technology syllabus",
      "syllabus",
      "timetable",
      "what is IT syllabus",
      "syllabus",
      "What is next lecture",
    ],
    responses: [
      'Timetable provide direct to the students OR To know about syllabus visit <a target="_blank" href="TIMETABLE LINK"> here</a>',
    ],
    context_set: "",
  },
  {
    tag: "library",
    patterns: [
      "is there any library",
      "library facility",
      "library facilities",
      "do you have library",
      "does the college have library facility",
      "college library",
      "where can i get books",
      "book facility",
      "Where is library",
      "Library",
      "Library information",
      "Library books information",
      "Tell me about library",
      "how many libraries",
    ],
    responses: [
      'There is one huge and spacious library.timings are 8am to 6pm and for more visit <a target="blank" href="ADD LIBRARY DETAIL LINK">here</a>',
    ],
    context_set: "",
  },
  {
    tag: "infrastructure",
    patterns: [
      "how is college infrastructure",
      "infrastructure",
      "college infrastructure",
    ],
    responses: [
      "Our University has Excellent Infrastructure. Campus is clean. Good IT Labs With Good Speed of Internet connection",
    ],
    context_set: "",
  },
  {
    tag: "canteen",
    patterns: [
      "food facilities",
      "canteen facilities",
      "canteen facility",
      "is there any canteen",
      "Is there a cafetaria in college",
      "Does college have canteen",
      "Where is canteen",
      "where is cafetaria",
      "canteen",
      "Food",
      "Cafetaria",
    ],
    responses: ["Our university has canteen with variety of food available"],
    context_set: "",
  },
  {
    tag: "menu",
    patterns: [
      "food menu",
      "food in canteen",
      "Whats there on menu",
      "what is available in college canteen",
      "what foods can we get in college canteen",
      "food variety",
      "What is there to eat?",
    ],
    responses: [
      "we serve Franky, Locho, Alu-puri, Kachori, Khavsa, Thaali and many more on menu",
    ],
    context_set: "",
  },
  {
    tag: "placement",
    patterns: [
      "What is college placement",
      "Which companies visit in college",
      "What is average package",
      "companies visit",
      "package",
      "About placement",
      "placement",
      "recruitment",
      "companies",
    ],
    responses: [
      'To know about placement visit <a target="_blank" href="PLACEMENT INFORMATION LINK FROM YOUR UNIVERSITY WEBSITE IF THEY HAVE">here</a>',
    ],
    context_set: "",
  },
  {
    tag: "ithod",
    patterns: ["Who is HOD", "Where is HOD", "it hod", "name of it hod"],
    responses: [
      "All engineering departments have only one hod XYZ who available on (Place name)",
    ],
    context_set: "",
  },
  {
    tag: "computerhod",
    patterns: [
      "Who is computer HOD",
      "Where is computer HOD",
      "computer hod",
      "name of computer hod",
    ],
    responses: [
      "All engineering departments have only one hod XYZ who available on (PLACE NAME)",
    ],
    context_set: "",
  },
  {
    tag: "extchod",
    patterns: [
      "Who is extc HOD",
      "Where is  extc HOD",
      "extc hod",
      "name of extc hod",
    ],
    responses: [
      "Different school wise hod are different.So be more clear with your school or department",
    ],
    context_set: "",
  },
  {
    tag: "principal",
    patterns: [
      "what is the name of principal",
      "whatv is the principal name",
      "principal name",
      "Who is college principal",
      "Where is principal's office",
      "principal",
      "name of principal",
    ],
    responses: [
      "XYZ is college principal and if you need any help then call your branch hod first.That is more appropriate",
    ],
    context_set: "",
  },
  {
    tag: "sem",
    patterns: [
      "exam dates",
      "exam schedule",
      "When is semester exam",
      "Semester exam timetable",
      "sem",
      "semester",
      "exam",
      "when is exam",
      "exam timetable",
      "exam dates",
      "when is semester",
    ],
    responses: [
      'Here is the Academic Calendar  <a target="_blank" href="YOUR ACADEMIC CALENDER">website</a>',
    ],
    context_set: "",
  },
  {
    tag: "admission",
    patterns: [
      "what is the process of admission",
      "what is the admission process",
      "How to take admission in your college",
      "What is the process for admission",
      "admission",
      "admission process",
    ],
    responses: [
      'Application can also be submitted online through the Unversity\'s  <a target="_blank" href="LINK OF ADMISSION DOCUMENT">website</a>',
    ],
    context_set: "",
  },
  {
    tag: "scholarship",
    patterns: [
      "scholarship",
      "Is scholarship available",
      "scholarship engineering",
      "scholarship it",
      "scholarship ce",
      "scholarship mechanical",
      "scholarship civil",
      "scholarship chemical",
      "scholarship for AI/ML",
      "available scholarships",
      "scholarship for computer engineering",
      "scholarship for IT engineering",
      "scholarship for mechanical engineering",
      "scholarship for civil engineering",
      "scholarship for chemical engineering",
      "list of scholarship",
      "comps scholarship",
      "IT scholarship",
      "mechanical scholarship",
      "civil scholarship",
      "chemical scholarship",
      "automobile scholarship",
      "first year scholarship",
      "second year scholarship",
      "third year scholarship",
      "fourth year scholarship",
    ],
    responses: [
      'Many government scholarships are supported by our university. For details and updates visit <a target="_blank" href="(SCHOLARSHIP DETAILS LINK)">here</a>',
    ],
    context_set: "",
  },
  {
    tag: "facilities",
    patterns: [
      "What facilities college provide",
      "College facility",
      "What are college facilities",
      "facilities",
      "facilities provided",
    ],
    responses: [
      "Our university's Engineering department provides fully AC Lab with internet connection, smart classroom, Auditorium, library,canteen",
    ],
    context_set: "",
  },
  {
    tag: "college intake",
    patterns: [
      "max number of students",
      "number of seats per branch",
      "number of seats in each branch",
      "maximum number of seats",
      "maximum students intake",
      "What is college intake",
      "how many stundent are taken in each branch",
      "seat allotment",
      "seats",
    ],
    responses: [
      "For IT, Computer and extc 60 per branch and seat may be differ for different department.",
    ],
    context_set: "",
  },
  {
    tag: "uniform",
    patterns: [
      "college dress code",
      "college dresscode",
      "what is the uniform",
      "can we wear casuals",
      "Does college have an uniform",
      "Is there any uniform",
      "uniform",
      "what about uniform",
      "do we have to wear uniform",
    ],
    responses: ["ENTER YOUR OWN UNIVERSITY UNIFORM CIRCULER"],
    context_set: "",
  },
  {
    tag: "committee",
    patterns: [
      "what are the different committe in college",
      "different committee in college",
      "Are there any committee in college",
      "Give me committee details",
      "committee",
      "how many committee are there in college",
    ],
    responses: [
      "For the various committe in college contact this number: ADD NUMBER",
    ],
    context_set: "",
  },
  {
    tag: "random",
    patterns: ["I love you", "Will you marry me", "Do you love me"],
    responses: ["I am not program for this, please ask appropriate query"],
    context_set: "",
  },
  {
    tag: "swear",
    patterns: [
      "fuck",
      "bitch",
      "shut up",
      "hell",
      "stupid",
      "idiot",
      "dumb ass",
      "asshole",
      "fucker",
    ],
    responses: [
      "please use appropriate language",
      "Maintaining decency would be appreciated",
    ],
    context_set: "",
  },
  {
    tag: "vacation",
    patterns: [
      "holidays",
      "when will semester starts",
      "when will semester end",
      "when is the holidays",
      "list of holidays",
      "Holiday in these year",
      "holiday list",
      "about vacations",
      "about holidays",
      "When is vacation",
      "When is holidays",
      "how long will be the vacation",
    ],
    responses: [
      "Academic calender is given to you by your class-soordinators after you join your respective classes",
    ],
    context_set: "",
  },
  {
    tag: "sports",
    patterns: [
      "sports and games",
      "give sports details",
      "sports infrastructure",
      "sports facilities",
      "information about sports",
      "Sports activities",
      "please provide sports and games information",
    ],
    responses: [
      'Our university encourages all-round development of students and hence provides sports facilities in the campus. For more details visit<a target="_blank" href=/"(LINK IF HAVE)">here</a>',
    ],
    context_set: "",
  },
  {
    tag: "salutaion",
    patterns: [
      "okk",
      "okie",
      "nice work",
      "well done",
      "good job",
      "thanks for the help",
      "Thank You",
      "its ok",
      "Thanks",
      "Good work",
      "k",
      "ok",
      "okay",
    ],
    responses: [
      "I am glad I helped you",
      "welcome, anything else i can assist you with?",
    ],
    context_set: "",
  },
  {
    tag: "task",
    patterns: [
      "what can you do",
      "what are the thing you can do",
      "things you can do",
      "what can u do for me",
      "how u can help me",
      "why i should use you",
    ],
    responses: [
      "I can answer to low-intermediate questions regarding college",
      "You can ask me questions regarding college, and i will try to answer them",
    ],
    context_set: "",
  },
  {
    tag: "ragging",
    patterns: [
      "ragging",
      "is ragging practice active in college",
      "does college have any antiragging facility",
      "is there any ragging cases",
      "is ragging done here",
      "ragging against",
      "antiragging facility",
      "ragging juniors",
      "ragging history",
      "ragging incidents",
    ],
    responses: [
      "We are Proud to tell you that our college provides ragging free environment, and we have strict rules against ragging",
    ],
    context_set: "",
  },
  {
    tag: "hod",
    patterns: ["hod", "hod name", "who is the hod"],
    responses: [
      "HODs differ for each branch, please be more specific like: (HOD it)",
    ],
    context_set: "",
  },
];
